server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: user-center-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/user-center
    username: root
    password: root